### PR TITLE
feat: speed up masternodes syncing

### PR DESCRIPTION
**Pull request by ktechmidas**
## Issue being fixed or feature implemented

I've modified the checks to not use mnsync status to check if the blockchain in synced as this can take up to an hour. Instead we check if headers == blocks (or we can check if verification > 0.99 if preferred)

Once synced we force mnsync next twice, checking each time that it's taken. Much like Dashmate does now

## What was done?

* Check blocks are synced
* Force mnsync next twice (once for the chain, once for the governance objects)
* Check the results

## How Has This Been Tested?

Deployed devnet-echo to test, worked like a charm.

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by ktechmidas** [comment]
I don't know if this is a chore or a fix... you decide :')

**Comment by shumkov** [comment]
> I don't know if this is a chore or a fix... you decide :')

There is a framework that will help you to decide https://www.conventionalcommits.org/en/v1.0.0/

**Comment by PastaPastaPasta** [comment]
What were the benchmarks between before and after?

**Comment by ktechmidas** [comment]
@PastaPastaPasta I didn't write down exact benchmarks, but this specific phase of the deployment will reach attempt 40-50 before continuing which means at least 40-50 minutes stuck here. This has been seen by both me and @strophy 

When deploying with this PR enabled it will not wait and get past these items in a few minutes. If you want me to do exact benchmarks before merging I'm happy to do it

**Review by shumkov — APPROVED** [review]
Looks good to me! 👍

**Review by strophy — APPROVED** [review]

**Pull request merged**
