### PR TITLE
feat: multifaucet promo codes

### PR DESCRIPTION
**Pull request by strophy**
## Issue being fixed or feature implemented

`faucet.testnet.networks.dash.org` did not support promo codes

## What was done?

Enable promo codes

## How Has This Been Tested?

On testnet

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by ktechmidas — APPROVED** [review]
LGTM

**Review by nmarley — COMMENTED** [review]
I _think_ we had decided several months ago on using only the other faucet and not this one (at least for testnet -- might be a good change for devnets). Are you planning to start using this one instead or alongside the other one we maintain?

**Comment by strophy** [comment]
I remember that too! I think we discovered that faucet.testnet.networks.dash.org has a bot that repeatedly attempts to drain the faucet - was this the reason we went with the other one? We tried for almost an hour to update the testnet-faucet.dash.org through terraform without success, so the thinking was that this one is easier to maintain because we understand how to do it while you are away @nmarley. Long term I think I would prefer pointing the other one at this one so we only have to maintain one faucet.

**Review by ktechmidas — APPROVED** [review]
LGTM

**Pull request merged**
