### PR TITLE
Chore: change spork activation command

### PR DESCRIPTION
**Pull request by ktechmidas**
## Issue being fixed or feature implemented
Core team have a new method for enabling sporks

## What was done?
Added new method for enabling sporks

## How Has This Been Tested?
Tested in various devnets, now that all devnets are testnet is < 18.1.0 we can go ahead and merge this change

## Breaking Changes
Deploy tool will no longer work on dashd versions < 18.1.0

## Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by nmarley** [comment]
I'm curious why this was closed -- seems like a useful proposal.

**Comment by ktechmidas** [comment]
Merging to the wrong branch, somehow included strophies 0.24-dev stuff here.

**Comment by nmarley** [comment]
@ktechmidas That's easy, just rebase those out. `git checkout sporkupdate && git rebase --onto v0.23-dev sporkupdate~1 sporkupdate && git push --force origin sporkupdate`.

I really think that as an org we need to take some time to learn our tools like git, this is not hard stuff, just takes a bit of time to learn to use it.

**Comment by nmarley** [comment]
GitHub won't let us re-use this PR since we force-pushed the branch after it was closed. If we'd re-opened it first it would have been fine (terrible UX @github, do better).

New PR: https://github.com/dashevo/dash-network-deploy/pull/365

**Pull request closed without merging**
