### PR TITLE
chore: ansible improvements

### PR DESCRIPTION
**Pull request by strophy**
## Issue being fixed or feature implemented

Errors and deprecation warnings were being thrown in ansible:
- Error processing new output from Terraform 1.0.5 update
- Error while testing Insight container status
- General difficulty reading errors
- Deprecation warning about Ansible `docker_container` community plugin syntax
- Deprecated package warnings
- Linter warnings

## What was done?

- Fix Terraform output
- Register variable before test and test correct variable
- Format output
- Specify future behaviour after default behaviour deprecation
- Update some packages and linter to resolve build warnings

## How Has This Been Tested?

Tested deploying `devnet-schnapps` with latest Terraform (1.0.5) and Ansible (2.11.4)

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by shumkov — APPROVED** [review]
LGTM! 👍

**Review by shumkov — CHANGES_REQUESTED** [review]
We need to update docker file and probably `ansible/requirements`

**Comment by strophy** [comment]
Dockerfile does not need updating because Ansible is installed from pip, which always has the latest versions. Ansible itself will update rapidly (mostly due to rolling release on 3 week schedule to always have up-to-date included community plugins) but ansible-core follows a more conservative release schedule and will through warnings and deprecations for many months before failing.

Ansible requirements have been updated and are tested on `devnet-schnapps`. Elastic was not updated yet due to licensing uncertainty and because 7.11.1 (last fully open source version) is still working fine, maybe we can do this separately if it becomes necssary.

**Review by shumkov — APPROVED** [review]
I see. Thank you. Then it looks good to me!

**Pull request merged**
